export const TEST_IDS = {
  appIdle: "app-idle",
  bootHold: "boot-hold",
  authLoading: "auth-loading",
  closeAccount: "close-account",
  screenNotFound: "screen-not-found",
  notFoundHome: "not-found-home",
  screenOnboarding: "screen-onboarding",
  buttonConnect: "button-connect",
  screenDeviceCode: "screen-device-code",
  deviceCodeUrl: "device-code-url",
  deviceCodeValue: "device-code-value",
  deviceCodeCancel: "device-code-cancel",
  screenUpNext: "screen-up-next",
  upNextList: "up-next-list",
  upNextSkeleton: "up-next-skeleton",
  upNextCard: (showId: number) => `up-next-card-${showId}`,
  upNextError: "up-next-error",
  markWatched: (showId: number) => `mark-watched-${showId}`,
  markState: (showId: number) => `mark-state-${showId}`,
  markPending: (showId: number) => `mark-pending-${showId}`,
  syncStrip: "sync-strip",
  syncStripOffline: "sync-strip-offline",
  syncStripError: "sync-strip-error",
  openAccount: "open-account",
  upNextEmpty: "up-next-empty",
  snackbar: "snackbar",
  snackbarMessage: "snackbar-message",
  screenHistory: "screen-history",
  historyList: "history-list",
  historyDay: "history-day",
  historyRow: "history-row",
  historyEmpty: "history-empty",
  screenSearch: "screen-search",
  searchInput: "search-input",
  searchResults: "search-results",
  searchRow: (traktId: number) => `search-row-${traktId}`,
  screenProfile: "screen-profile",
  profileEpisodeCount: "profile-episode-count",
  profileToHistory: "profile-to-history",
  profileToSettings: "profile-to-settings",
  runtimeError: "runtime-error",
  runtimeErrorRetry: "runtime-error-retry",
  runtimeLoading: "runtime-loading",
  screenSettings: "screen-settings",
  settingsHaptics: "settings-haptics",
  settingsVersion: "settings-version",
  settingsDisconnect: "settings-disconnect",
  episodeSkeleton: "episode-skeleton",
  screenEpisode: "screen-episode",
  episodeCode: "episode-code",
  episodeWatched: "episode-watched",
  movieDetailSkeleton: "movie-detail-skeleton",
  screenMovieDetail: "screen-movie-detail",
  movieYear: "movie-year",
  screenLibrary: "screen-library",
  librarySegment: "library-segment",
  libraryList: "library-list",
  libraryRow: (traktId: number) => `library-row-${traktId}`,
  calendarSkeleton: "calendar-skeleton",
  screenCalendar: "screen-calendar",
  calendarList: "calendar-list",
  calendarDay: "calendar-day",
  calendarRow: (traktId: number) => `calendar-row-${traktId}`,
  calendarEmpty: "calendar-empty",
  showDetailSkeleton: "show-detail-skeleton",
  screenShowDetail: "screen-show-detail",
  showProgress: "show-progress",
  seasonList: "season-list",
  seasonRow: (season: number) => `season-row-${season}`,
  episodeRow: (traktId: number) => `episode-row-${traktId}`,
} as const;
