export const TEST_IDS = {
  appIdle: "app-idle",
  startupTiming: "startup-timing",
  bootHold: "boot-hold",
  authLoading: "auth-loading",
  closeAccount: "close-account",
  screenNotFound: "screen-not-found",
  notFoundHome: "not-found-home",
  screenOnboarding: "screen-onboarding",
  buttonConnect: "button-connect",
  screenDeviceCode: "screen-device-code",
  deviceCodeUrl: "device-code-url",
  deviceCodeValue: "device-code-value",
  deviceCodeCancel: "device-code-cancel",
  screenUpNext: "screen-up-next",
  upNextList: "up-next-list",
  upNextSkeleton: "up-next-skeleton",
  upNextError: "up-next-error",
  upNextErrorRetry: "up-next-error-retry",
  upNextTvOff: "up-next-tv-off",
  watchlistTile: "watchlist-tile",
  marqueeCard: "marquee-card",
  marqueeMark: "marquee-mark",
  queueRow: (traktId: number) => `queue-row-${traktId}`,
  queueRowMark: (traktId: number) => `queue-row-${traktId}-mark`,
  lapsedDrawerToggle: "lapsed-drawer-toggle",
  lapsedRow: (traktId: number) => `lapsed-row-${traktId}`,
  lapsedRowMark: (traktId: number) => `lapsed-row-${traktId}-mark`,
  onTheWayList: "on-the-way-list",
  upNextEmptyNothingQueued: "up-next-empty-nothing-queued",
  upNextEmptyAllCaughtUp: "up-next-empty-all-caught-up",
  upNextEmptyNothingStarted: "up-next-empty-nothing-started",
  upNextEmptyOnlyStopped: "up-next-empty-only-stopped",
  tutorialCaption: "tutorial-caption",
  syncStrip: "sync-strip",
  syncStripOffline: "sync-strip-offline",
  syncStripError: "sync-strip-error",
  refreshIndicator: "refresh-indicator",
  quickActions: "quick-actions",
  quickActionMark: "quick-action-mark",
  quickActionStop: "quick-action-stop",
  quickActionDetails: "quick-action-details",
  syncNow: "sync-now",
  avatarLink: "avatar-link",
  linkHistory: "link-history",
  snackbar: "snackbar",
  snackbarMessage: "snackbar-message",
  snackbarUndo: "snackbar-undo",
  screenHistory: "screen-history",
  historyList: "history-list",
  historyDay: "history-day",
  historyRow: "history-row",
  historyEmpty: "history-empty",
  screenSearch: "screen-search",
  screenProfile: "screen-profile",
  profileEpisodeCount: "profile-episode-count",
  profileToHistory: "profile-to-history",
  profileToSettings: "profile-to-settings",
  runtimeError: "runtime-error",
  runtimeErrorRetry: "runtime-error-retry",
  runtimeLoading: "runtime-loading",
  screenSettings: "screen-settings",
  settingsHaptics: "settings-haptics",
  settingsVersion: "settings-version",
  settingsDisconnect: "settings-disconnect",
  episodeSkeleton: "episode-skeleton",
  screenEpisode: "screen-episode",
  episodeCode: "episode-code",
  episodeWatched: "episode-watched",
  movieDetailSkeleton: "movie-detail-skeleton",
  screenMovieDetail: "screen-movie-detail",
  movieYear: "movie-year",
  screenLibrary: "screen-library",
  screenCalendar: "screen-calendar",
  showDetailSkeleton: "show-detail-skeleton",
  screenShowDetail: "screen-show-detail",
  showProgress: "show-progress",
  seasonList: "season-list",
  seasonRow: (season: number) => `season-row-${season}`,
  episodeRow: (traktId: number) => `episode-row-${traktId}`,
} as const;
