// Generated by scripts/write-buster.mjs. Run `pnpm buster:bump` to update.
/**
 * The persisted-cache buster and the shape it was last bumped for. Any cache
 * written under a different `buster` is dropped rather than replayed: under
 * `staleTime: Infinity`, with freshness gated only on `/sync/last_activities`,
 * a forgotten bump after a shape change is silent, permanent corruption with no
 * self-heal path. This, not an age cap, is how stale snapshots are retired.
 *
 * `pnpm buster:check` recomputes `shape` and fails while the two disagree, so a
 * forgotten bump is a build failure rather than a silent one. The two fields
 * differ only between the commit that introduced this file and the first genuine
 * shape change after it.
 */
export const PERSISTED_CACHE = {
  buster: "d0c3d97c58b8",
  shape: "280cd07e45e0",
} as const;
