#!/usr/bin/env node
// Usage: write-buster.mjs --check | --bump
//
// The persisted-cache buster (query-client.ts) and the shape witness it is
// keyed to. `--check` recomputes the witness and fails when the committed one
// disagrees; `--bump` writes both literals to the recomputed witness.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

/**
 * The trees that DEFINE every persisted shape. `runtime` types every cached
 * value and those types resolve entirely into `data` and `domain`, so no shape a
 * restored cache is replayed against can change without changing a byte here.
 * Moving a file between these trees, or into a package, is not a shape change,
 * so these roots may be repathed without bumping anything.
 */
const SHAPE_TREES = [
  "packages/web/src/domain",
  "packages/web/src/data",
  "packages/web/src/ui/runtime",
];

const GENERATED = "packages/web/src/ui/runtime/persist-buster.ts";

/**
 * Every module specifier in an `import`, `export ... from`, dynamic `import()`
 * or `require()` clause, collapsed to one constant before hashing. A refactor
 * that respells `@domain/up-next` as `@cue/core/domain/up-next` rewrites nearly
 * every file in these trees and changes no persisted shape; without this the
 * rename alone would drop every shipping user's cache.
 */
const MODULE_SPECIFIER = /(?<![.\w$])(from|import|require)(\s*\(?\s*)(["'])(?:[^"'\\\n]|\\.)*?\3/g;

function filesUnder(tree) {
  const root = join(ROOT, tree);
  return readdirSync(root, { recursive: true, encoding: "utf8" })
    .map((entry) => join(tree, entry))
    .filter((path) => statSync(join(ROOT, path)).isFile() && path !== GENERATED);
}

/**
 * A digest per file, sorted, then hashed. No path component enters the hash, so
 * a file that moves between the trees produces the same witness; a file added,
 * deleted or edited does not.
 */
function shapeWitness() {
  const digests = SHAPE_TREES.flatMap(filesUnder)
    .map((path) =>
      createHash("sha256")
        .update(readFileSync(join(ROOT, path), "utf8").replace(MODULE_SPECIFIER, '$1$2$3"$3'))
        .digest("hex"),
    )
    .sort();
  const hash = createHash("sha256");
  for (const digest of digests) hash.update(digest);
  return hash.digest("hex").slice(0, 12);
}

const generatedPath = join(ROOT, GENERATED);
const readField = (name) => {
  const source = readFileSync(generatedPath, "utf8");
  const match = source.match(new RegExp(`\\b${name}: "([0-9a-f]{12})"`));
  if (!match) throw new Error(`${GENERATED} carries no ${name} field`);
  return match[1];
};

const computed = shapeWitness();
const mode = process.argv[2];

if (mode === "--check") {
  const shape = readField("shape");
  if (shape !== computed) {
    process.stderr.write(
      `buster:check failed: committed shape ${shape}, computed ${computed}.\n` +
        "A persisted shape changed. Run `pnpm buster:bump` and commit the result.\n",
    );
    process.exit(1);
  }
  process.stdout.write(`buster:check ok (shape ${shape}, buster ${readField("buster")})\n`);
} else if (mode === "--bump") {
  writeFileSync(generatedPath, render(computed, computed));
  process.stdout.write(`buster:bump wrote shape ${computed}, buster ${computed}\n`);
} else {
  process.stderr.write("Usage: write-buster.mjs --check | --bump\n");
  process.exit(2);
}

function render(buster, shape) {
  return `// Generated by scripts/write-buster.mjs. Run \`pnpm buster:bump\` to update.
/**
 * The persisted-cache buster and the shape it was last bumped for. Any cache
 * written under a different \`buster\` is dropped rather than replayed: under
 * \`staleTime: Infinity\`, with freshness gated only on \`/sync/last_activities\`,
 * a forgotten bump after a shape change is silent, permanent corruption with no
 * self-heal path. This, not an age cap, is how stale snapshots are retired.
 *
 * \`pnpm buster:check\` recomputes \`shape\` and fails while the two disagree, so a
 * forgotten bump is a build failure rather than a silent one. The two fields
 * differ only between the commit that introduced this file and the first genuine
 * shape change after it.
 */
export const PERSISTED_CACHE = {
  buster: "${buster}",
  shape: "${shape}",
} as const;
`;
}
